name: Build and deploy .NET Core app to Azure

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_PACKAGE_PATH: 'Contacts' # set this to the path to your web app project
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Contacts.csproj

    - name: Build
      run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Contacts.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Contacts.csproj --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Contacts.csproj --configuration Release --no-build -o ./build_output

    - uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: ./build_output

  deploy-dev:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.webapp-url }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy-to-azure
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package-path: ./build_output

  deploy-test:
    needs: deploy-dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: test
      url: ${{ steps.deploy.outputs.webapp-url }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy-to-azure
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package-path: ./build_output

  deploy-prod:
    needs: deploy-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ steps.deploy.outputs.webapp-url }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy-to-azure
      with:
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package-path: ./build_output
